
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class BookPanel extends javax.swing.JPanel {
    
    private String btitle;
    private String bauthor;
    private String bcategory;
    private double price;
    private byte[] image;
    private int id;
    
    public void setId(int id){
        this.id=id;
    }
    public int getId(){
        return id;
    }
    
    public void setBtitle(String btitle){
        this.btitle=btitle;
    }
    public String getBtitle(){
        return btitle;
    }
    
    public void setBauthor(String bauthor){
        this.bauthor=bauthor;
    }
    public String getBauthor(){
        return bauthor;
    }
    
    public void setBCategory(String bcategory){
        this.bcategory=bcategory;
    }
    public String getBcategory(){
        return bcategory;
    }
    
    public void setPrice(double price){
        this.price=price;
    }
    public double getPrice(){
        return price;
    }
    
    public void setImage(byte[] image){
        this.image=image;
    }
    public ImageIcon getImage(){
        ImageIcon MyImage=new ImageIcon(image);
        Image img=MyImage.getImage();
        Image newImg=img.getScaledInstance(120, 140,Image.SCALE_SMOOTH);
        ImageIcon new_image=new ImageIcon(newImg);
        
        return new_image;
    }

    /**
     * Creates new form NewJPanel
     */
    public BookPanel() {
        initComponents();
    }
    
     public BookPanel(final int BookID,String btitle,String bauthor,String bcategory,double price,byte[] image,final String address_session){
         initComponents();
         btnBuy.addActionListener(new ActionListener(){
             @Override
             public void actionPerformed(ActionEvent e) {
                 
        View view = new View(address_session);
        mainproject mp=new mainproject();
        mp.dispose();
        view.setVisible(true);
                
             }
             
         });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAuthor = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        lblTitleSet = new javax.swing.JLabel();
        lblAuthorSet = new javax.swing.JLabel();
        lblPriceSet = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        lblCategorySet = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblTitle.setText("Title:");

        lblAuthor.setText("Author:");

        lblPrice.setText("Price($):");

        btnBuy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(0, 204, 51));
        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });

        lblTitleSet.setFont(new java.awt.Font("Zawgyi-One", 0, 11)); // NOI18N
        lblTitleSet.setText("unknown");

        lblAuthorSet.setFont(new java.awt.Font("Zawgyi-One", 0, 11)); // NOI18N
        lblAuthorSet.setText("unknown");

        lblPriceSet.setFont(new java.awt.Font("Zawgyi-One", 0, 11)); // NOI18N
        lblPriceSet.setText("unknown");

        lblCategory.setText("Categoery:");

        lblCategorySet.setFont(new java.awt.Font("Zawgyi-One", 0, 11)); // NOI18N
        lblCategorySet.setText("unknown");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblAuthor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblCategory))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblPrice)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAuthorSet)
                            .addComponent(lblCategorySet)
                            .addComponent(lblPriceSet)
                            .addComponent(lblTitleSet, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnBuy)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblTitleSet))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAuthor)
                    .addComponent(lblAuthorSet))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCategory)
                    .addComponent(lblCategorySet))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrice)
                    .addComponent(lblPriceSet))
                .addGap(8, 8, 8)
                .addComponent(btnBuy)
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAuthor;
    public javax.swing.JLabel lblAuthorSet;
    private javax.swing.JLabel lblCategory;
    public javax.swing.JLabel lblCategorySet;
    public javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblPrice;
    public javax.swing.JLabel lblPriceSet;
    private javax.swing.JLabel lblTitle;
    protected javax.swing.JLabel lblTitleSet;
    // End of variables declaration//GEN-END:variables

    
}
